import os
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_OLLAMA_HOST = "localhost:13434"

STAGING_FILENAME = "knowledge_graph_partial.json"
CLEANED_FILENAME = "knowledge_graph_cleaned.json"
CURATED_FILENAME = "knowledge_graph_autogenerated.json"
VIEWER_FILENAME = "knowledge_graph.html"

NOISY_LOGGERS = ("docling", "docling_core", "docling_ibm_models", "PIL")
NOISY_WARNING_MODULES = (r"docling.*", r"PIL.*")


def resolve_host(value: str | None = None) -> str:
    host = value or os.environ.get("OLLAMA_HOST") or DEFAULT_OLLAMA_HOST
    return host if host.startswith(("http://", "https://")) else f"http://{host}"


@dataclass
class BuilderConfig:
    extraction_model: str = "gemma4:31b-it-q4_K_M"
    curation_model: str = "gemma4:31b-it-q4_K_M"
    repair_model: str = "gemma4:e4b-it-q4_K_M"

    inference_engine: str = "ollama"
    ollama_host: str = field(default_factory=resolve_host)
    request_timeout: float = 600.0

    chunk_size: int = 16_000
    max_repair_attempts: int = 3
    max_evidence_relations: int = 6

    merge_qualifier_pattern: str | None = None
    plural_suffixes: tuple[str, ...] = ("s",)
    unclassified_domain: str = "Unclassified"

    output_dir: Path = Path("output")

    def __post_init__(self):
        self.ollama_host = resolve_host(self.ollama_host)
        self.output_dir = Path(self.output_dir)

    @property
    def models(self) -> tuple[str, ...]:
        return tuple(
            dict.fromkeys((self.extraction_model, self.curation_model, self.repair_model))
        )

    @property
    def staging_path(self) -> Path:
        return self.output_dir / STAGING_FILENAME

    @property
    def cleaned_path(self) -> Path:
        return self.output_dir / CLEANED_FILENAME

    @property
    def curated_path(self) -> Path:
        return self.output_dir / CURATED_FILENAME

    @property
    def viewer_path(self) -> Path:
        return self.output_dir / VIEWER_FILENAME
